### ISSUE TITLE
Fails to deploy

### ISSUE THREAD

**Issue by jtb368** [watson-developer-cloud/personality-insights-python#8]
Hi, trying to deploy to Bluemix. Fails on the error 'Could not find service personality-insights-service'. Please advise

**Comment by nfriedly** [comment]
Hi @jtb368, did you complete step 5 in the instructions:

>  5\. Create the Personality Insights service in Bluemix
> 
> `$ cf create-service personality_insights standard personality-insights-service`

And, did it give any errors?

**Comment by germanattanasio** [comment]
The new personality insights plan is `tiered` not `standard` I've updated the instructions and the `manifest.yml` file
